### ISSUE TITLE
sjackzx - Problem starting boa constructor?

### ISSUE THREAD

**Issue by ianBBB** [ianBBB/boa-constructor#17]
I have one error on the run boa Construccion i use python 310 and sender this error:
```
Traceback (most recent call last):
File "C:\boa-constructor-master\boa.py", line 577, in OnInit
editor = Editor.EditorFrame(self.main, -1, inspector, wx.Menu(),
File "C:\boa-constructor-master\Editor.py", line 188, in init
self.explorer.tree.openDefaultNodes()
File "C:\boa-constructor-master\Explorers\Explorer.py", line 354, in openDefaultNodes
self.Expand(bktn)
wx._core.wxAssertionError: C++ assertion ""item.IsOk()"" failed at ....\src\msw\treectrl.cpp(1314) in wxTreeCtrl::IsExpanded(): invalid tree item
OnInit returned false, exiting...
```

**Comment by ianBBB** [comment]
Could I get more details please.
_I have assumed this occurred during startup. Is that correct?
Also, what operating system are you using?
And also, did this happen once or does it happen all the time?_
If you could help me with these questions that would be great.

**Comment by sjackzx** [comment]
yes  only  occurred  during startup the program , i work on SO  Win 10 . ok that app  show the first  windows Gauge and stop the program and exit or end the program no do it more

**Comment by ianBBB** [comment]
I know this is an old one but I am checking over the Issues list to sort out what has been fixed and what still needs attention now that we have an official release.
A lot of work has occurred since this report and at some point through that, I had Boa starting and working fine on Windows 10. That was a while ago now and I have moved over to doing testing on Windows 11. 
I am pretty sure the current release of Boa Constructor work on Windows 10 so I am going to close this Issue but if you still have trouble, please re-open the Issue.
