### ISSUE TITLE
Print button on the Editor does not work.

### ISSUE THREAD

**Issue by ianBBB** [ianBBB/boa-constructor#6]
and produces this error message;

_Traceback (most recent call last):
File "C:\Users\Ian-17\PycharmProjects\boa-constructor\Views\SourceViews.py", line 541, in OnPrint
dlg = STCPrinting.STCPrintDlg(self.model.editor, self, self.model.filename)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Ian-17\PycharmProjects\boa-constructor\Views\STCPrinting.py", line 90, in init
self._init_ctrls(parent)
File "C:\Users\Ian-17\PycharmProjects\boa-constructor\Views\STCPrinting.py", line 50, in init_ctrls
self.rdbColourMode = wx.RadioBox(choices=[('Normal'), ('Black on white'),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RadioBox(): arguments did not match any overloaded call:
overload 1: 'choices' is not a valid keyword argument
overload 2: 'point' is not a valid keyword argument

**Comment by ianBBB** [comment]
Have worked on this at various times recently and printing function is now restored.
